# Generated by Django 5.1.3 on 2024-11-19 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_hotels_description_hotels_latitude_hotels_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotels",
            name="tel",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number. Allowed formats: +1234567890, +1 234 567 890, etc.",
                        regex="^\\+?[0-9\\s\\-\\(\\)]{9,20}$",
                    )
                ],
            ),
        ),
    ]
