# Generated by Django 5.1.3 on 2024-11-19 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_alter_hotels_tel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hotels",
            new_name="Hotel",
        ),
    ]
