# Generated by Django 5.1.3 on 2024-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_rename_hotels_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hotels/"),
                ),
                ("job_time", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
