# Generated by Django 5.1.3 on 2024-11-20 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0005_hotel_information"),
        ("hotels", "0005_mehmonxona"),
    ]

    operations = []
