# Generated by Django 5.1.3 on 2024-11-20 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0006_merge_0005_hotel_information_0005_mehmonxona"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mehmonxona",
            new_name="Hotels",
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.AddField(
            model_name="hotel_information",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel_information",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel_information",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel_information",
            name="star_rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel_information",
            name="tel",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number. Allowed formats: +1234567890, +1 234 567 890, etc.",
                        regex="^\\+?[0-9\\s\\-\\(\\)]{9,20}$",
                    )
                ],
            ),
        ),
    ]
