# Generated by Django 5.1.3 on 2024-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("jop_time", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="images/")),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name="Restoran_malumotlari",
            new_name="Restaurant_info",
        ),
        migrations.DeleteModel(
            name="Restoranlar",
        ),
    ]
